### ISSUE TITLE
+$1 should render as a plus sign followed by the coin icon

### ISSUE THREAD

**Issue by robinmoussu** [shardofhonor/dominion-card-generator#12] opened 2021-06-04 22:36 UTC
Currently using `+$1` in the description will not display the treasure icon but a literal $. The same applies for all other kind of icon (like potion or victory point).

To circumvent it, you can add a space between the `+` and the icon, like in `+ $1`, but then a space will render between the `+` and the icon.

**Comment by shardofhonor** [comment] 2021-10-04 16:14
Sorry, I could not reproduce the error. For example [Market](http://wiki.dominionstrategy.com/index.php/Market) seems to be [working just fine](https://shardofhonor.github.io/dominion-card-generator/?title=Market&description=%2B1%20Card%0A%2B1%20Action%0A%2B1%20Buy%0A%2B%241%0A&type=Action&credit=&creator=&price=%245&preview=&type2=&color2split=1&boldkeys=Action&picture-x=0&picture-y=0&picture-zoom=1&picture=http%3A%2F%2Fwiki.dominionstrategy.com%2Fimages%2F2%2F24%2FMarketArt.jpg&expansion=http%3A%2F%2Fwiki.dominionstrategy.com%2Fimages%2Fthumb%2Fb%2Fb0%2FDominion_icon.png%2F22px-Dominion_icon.png&custom-icon=&color0=0&color1=0&size=0). The error might have been fixed in the meantime.

**Closed as completed by shardofhonor** 2021-10-04 16:14 UTC
